// ABOUTME: Bootstrap rules by mining Claude Code JSONL session transcripts.
// ABOUTME: Discovers command patterns and outputs as a table or TOML rule stubs.

const std = @import("std");
const transcript = @import("../claude/transcript.zig");
const settings_mod = @import("../claude/settings.zig");
const shell = @import("../engine/shell.zig");
const Table = @import("../display/table.zig").Table;

pub const ScanOptions = struct {
    project_path: ?[]const u8 = null, // defaults to cwd
    global: bool = false,
    min_count: u32 = 1,
    output_toml: bool = false,
    permissions: bool = false,
};

const CommandStats = struct {
    count: u64,
    last_seen: ?[]const u8,
};

const Entry = struct { cmd: []const u8, stats: CommandStats };

/// Run scan against JSONL content directly (used by tests and the CLI).
pub fn scanContent(
    allocator: std.mem.Allocator,
    content: []const u8,
    opts: ScanOptions,
    settings: ?settings_mod.SettingsReader,
    writer: anytype,
) !u8 {
    var commands = try transcript.extractCommands(allocator, content);
    defer transcript.freeCommands(allocator, &commands);

    if (commands.items.len == 0) {
        try writer.print("No Bash commands found in transcripts.\n", .{});
        return 0;
    }

    // Aggregate by base command
    var freq = std.StringHashMap(CommandStats).init(allocator);
    defer freq.deinit();

    for (commands.items) |cmd| {
        // Extract base command (first word)
        var iter = std.mem.splitScalar(u8, cmd.command, ' ');
        const base = iter.first();

        const gop = try freq.getOrPut(base);
        if (gop.found_existing) {
            gop.value_ptr.count += 1;
            gop.value_ptr.last_seen = cmd.timestamp;
        } else {
            gop.value_ptr.* = .{ .count = 1, .last_seen = cmd.timestamp };
        }
    }

    // Collect and sort by count descending
    var entries = std.ArrayListUnmanaged(Entry).empty;
    defer entries.deinit(allocator);

    var iter = freq.iterator();
    while (iter.next()) |kv| {
        if (kv.value_ptr.count >= opts.min_count) {
            try entries.append(allocator, .{ .cmd = kv.key_ptr.*, .stats = kv.value_ptr.* });
        }
    }

    std.mem.sort(Entry, entries.items, {}, struct {
        fn cmp(_: void, a: Entry, b: Entry) bool {
            return a.stats.count > b.stats.count;
        }
    }.cmp);

    if (entries.items.len == 0) {
        try writer.print("No commands found matching filters.\n", .{});
        return 0;
    }

    if (opts.output_toml) {
        try outputToml(entries.items, writer);
    } else {
        try outputTable(allocator, entries.items, settings, writer);
    }

    return 0;
}

fn outputTable(
    allocator: std.mem.Allocator,
    entries: []const Entry,
    settings: ?settings_mod.SettingsReader,
    writer: anytype,
) !void {
    const headers = if (settings != null)
        &[_][]const u8{ "Command", "Count", "Last Seen", "Permission" }
    else
        &[_][]const u8{ "Command", "Count", "Last Seen" };

    var table = Table{ .headers = headers };
    defer table.deinit(allocator);

    var count_buf: [32]u8 = undefined;

    for (entries) |entry| {
        const count_str = std.fmt.bufPrint(&count_buf, "{d}", .{entry.stats.count}) catch "?";
        const last = entry.stats.last_seen orelse "unknown";

        if (settings) |s| {
            const perm = s.classify(entry.cmd);
            const perm_str = @tagName(perm);
            try table.addRow(allocator, &.{ entry.cmd, count_str, last, perm_str });
        } else {
            try table.addRow(allocator, &.{ entry.cmd, count_str, last });
        }
    }

    try table.render(writer);
}

fn outputToml(
    entries: []const Entry,
    writer: anytype,
) !void {
    try writer.print("# Auto-generated by veer scan\n", .{});
    try writer.print("# Review and customize before adding to your config\n\n", .{});

    for (entries) |entry| {
        try writer.print("[[rule]]\n", .{});
        try writer.print("id = \"redirect-{s}\"\n", .{entry.cmd});
        try writer.print("name = \"Redirect {s}\"\n", .{entry.cmd});
        try writer.print("action = \"reject\"\n", .{});
        try writer.print("message = \"Consider using a project-specific command instead of `{s}`.\"\n", .{entry.cmd});
        try writer.print("# Seen {d} times\n", .{entry.stats.count});
        try writer.print("[rule.match]\n", .{});
        try writer.print("command = \"{s}\"\n\n", .{entry.cmd});
    }
}

// -- Tests --

test "scanContent extracts and aggregates commands" {
    const content = transcript.test_jsonl;

    var buf: [4096]u8 = undefined;
    var stream = std.io.fixedBufferStream(&buf);

    const exit_code = try scanContent(std.testing.allocator, content, .{}, null, stream.writer());

    try std.testing.expectEqual(@as(u8, 0), exit_code);
    const output = stream.getWritten();
    try std.testing.expect(std.mem.indexOf(u8, output, "pytest") != null);
    try std.testing.expect(std.mem.indexOf(u8, output, "just") != null);
    try std.testing.expect(std.mem.indexOf(u8, output, "python3") != null);
}

test "scanContent with min-count filter" {
    const content = transcript.test_jsonl;

    var buf: [4096]u8 = undefined;
    var stream = std.io.fixedBufferStream(&buf);

    // pytest appears twice, others once. min_count=2 should only show pytest
    const exit_code = try scanContent(std.testing.allocator, content, .{ .min_count = 2 }, null, stream.writer());

    try std.testing.expectEqual(@as(u8, 0), exit_code);
    const output = stream.getWritten();
    try std.testing.expect(std.mem.indexOf(u8, output, "pytest") != null);
    try std.testing.expect(std.mem.indexOf(u8, output, "python3") == null);
}

test "scanContent toml output" {
    const content = transcript.test_jsonl;

    var buf: [4096]u8 = undefined;
    var stream = std.io.fixedBufferStream(&buf);

    const exit_code = try scanContent(std.testing.allocator, content, .{ .output_toml = true }, null, stream.writer());

    try std.testing.expectEqual(@as(u8, 0), exit_code);
    const output = stream.getWritten();
    try std.testing.expect(std.mem.indexOf(u8, output, "[[rule]]") != null);
    try std.testing.expect(std.mem.indexOf(u8, output, "command = ") != null);
    try std.testing.expect(std.mem.indexOf(u8, output, "Auto-generated") != null);
}

test "scanContent with permissions" {
    const jsonl = transcript.test_jsonl;
    const settings_json = "{\"allowedTools\": [\"Bash(just *)\", \"Read\"], \"deniedTools\": [\"Bash(python3:*)\", \"Bash(rm:*)\", \"Bash(pytest:*)\"]}";

    var reader = try settings_mod.SettingsReader.loadString(std.testing.allocator, settings_json);
    defer reader.deinit();

    var buf: [4096]u8 = undefined;
    var stream = std.io.fixedBufferStream(&buf);

    const exit_code = try scanContent(std.testing.allocator, jsonl, .{ .permissions = true }, reader, stream.writer());

    try std.testing.expectEqual(@as(u8, 0), exit_code);
    const output = stream.getWritten();
    // Should have Permission column
    try std.testing.expect(std.mem.indexOf(u8, output, "Permission") != null);
    try std.testing.expect(std.mem.indexOf(u8, output, "denied") != null);
}

test "scanContent with empty input" {
    var buf: [256]u8 = undefined;
    var stream = std.io.fixedBufferStream(&buf);

    const exit_code = try scanContent(std.testing.allocator, "", .{}, null, stream.writer());

    try std.testing.expectEqual(@as(u8, 0), exit_code);
    const output = stream.getWritten();
    try std.testing.expect(std.mem.indexOf(u8, output, "No Bash commands") != null);
}
